version: '3.9'
services:
  nats-streaming:
    container_name: nats-streaming
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - NATS_STREAMING_CLUSTER_ID=test-cluster
      - NATS_STREAMING_STORE_TYPE=file
      - NATS_STREAMING_FILE_STORE_DIR=/data/stan/store
    volumes:
      - ./pkg/repository/nats/data:/data/stan/store
    restart: always
    networks:
      - l0_my-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - nats-streaming
    env_file: .env
    networks:
      - l0_my-network

networks:
  l0_my-network:
    driver: bridge
